---
version: '3'
services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/ruby_app:cached
    ports:
      - "3000:3000"
    # depends_on:
    #   - rabbitmq
    #   - swift
    env_file: .env
